# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mspe_FH_McJack <- function(m, X, Y, D, bhat, Ahat, K, maxiter) {
    .Call(`_smaFHNER_mspe_FH_McJack`, m, X, Y, D, bhat, Ahat, K, maxiter)
}

mspe_FH_Jackknife <- function(p, m, X, Y, D, bhat, A_REML, maxiter) {
    .Call(`_smaFHNER_mspe_FH_Jackknife`, p, m, X, Y, D, bhat, A_REML, maxiter)
}

mspe_FH_PB <- function(X, Y, D, K) {
    .Call(`_smaFHNER_mspe_FH_PB`, X, Y, D, K)
}

mspe_FH_DB <- function(X, y, D, K, C, b, Ahat, maxiter) {
    .Call(`_smaFHNER_mspe_FH_DB`, X, y, D, K, C, b, Ahat, maxiter)
}

mspe_FH_Sucma <- function(p, m, X, Y, D, bhat, A_REML, K) {
    .Call(`_smaFHNER_mspe_FH_Sucma`, p, m, X, Y, D, bhat, A_REML, K)
}

